export default {
  FETCHING_CARTLIST_START: 'FETCHING_CARTLIST_START',
  FETCHING_CARTLIST_SUCCESS: 'FETCHING_CARTLIST_SUCCESS',
  FETCHING_CARTLIST_FAILED: 'FETCHING_CARTLIST_FAILED',
  ON_ITEM_ADD: 'ON_ITEM_ADD',
  ON_ITEM_REMOVE: 'ON_ITEM_REMOVE',
  ON_COUNTER_CHANGE: 'ON_COUNTER_CHANGE'
};
